### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/GitAPI#2]
you made, a git api, this is going to be a big one, but maybe we should finish replapi before gitapi?

**Comment by kokonut27** [comment]
yes, lol, ik. XD

**Comment by kokonut27** [comment]
ima prob work on replapi for now. gitapi will prob take a few months lol

**Comment by darkdarcool** [comment]
lol it will, ill work on replapi now on and off. Feel free to ping me
