### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/GitAPI#4]
https://github.com/JBYT27/GitAPI/blob/e9b875b8a1046f7ef61eddb1e3887697b609da62/MyApp/git_api/main.py#L17

How the frick are you going to get data from that link? Use: https://api.github.com/users/theUsersName

**Comment by kokonut27** [comment]
I'm planning on webscraping all the data lol. 
If I use the API the github already has, what's the point in using it? Like I'm planning on making my own API module, so shouldn't I use my own kind of scraping or smth? 
Basically, my plan is to we scrape without using the API github already has. 
> it'll probably take a super long time lol

**Comment by darkdarcool** [comment]
Ye, probably not going to be efficient, but eh, maybe you'll get some special data?

**Comment by kokonut27** [comment]
Yeah, maybe

**Comment by darkdarcool** [comment]
Well if you need help, lemme know!
