### ISSUE TITLE
[ENHANCEMENT] Add more advanced functions to GitAPI

### ISSUE THREAD

**Issue by kokonut27** [JBYT27/GitAPI#7]
Add more functions to User class. 

Pretty high priority right now.

**Comment by darkdarcool** [comment]
Take a look at the official GitHub docs for its graphql [here](https://docs.github.com/en/graphql/reference)(pick one of the options there, I suggest queries, but if you want it to be even more advanced, look at some of the others), as it gives you so many options on what data to get, and not just on the user

**Comment by kokonut27** [comment]
Oh, okay! Thanks so much!

**Comment by darkdarcool** [comment]
Your welcome! If you need any help, I'm an ~~expert~~, ~~trash~~, mediocre at GitHub queries!

**Comment by kokonut27** [comment]
LMAO, okay!

**Comment by kokonut27** [comment]
Heya @darkdarcool, I need help with using and finding the `repository` query. I'm trying combinations to try and make a function, but I'm pretty much stuck here. 

Could you take a look at my code in `main.py`?
Thanks!

**Comment by darkdarcool** [comment]
Look at what I did for gitapi https://github.com/GitAPI-it/GitAPI.it-Nodejs/blob/main/src/core/main/utils/query_list.js#L84

**Comment by kokonut27** [comment]
Oh, okay! Thanks so much!
